#!/usr/bin/env bash
# Regenerate the gitignored config_secrets.py from Doppler.
#
# Source of truth: Doppler project `common`, config `dev` (shared across
# projects - the house WiFi is not specific to this repo). Run once after a
# container rebuild, or whenever the credentials change:
#
#     ./scripts/gen-secrets.sh
#
# config_secrets.py is gitignored, so this file - not the secret - is what
# survives in git. The board needs a real file on its filesystem, so the
# generated output is then deployed with `mpremote fs cp config_secrets.py :`.
set -euo pipefail

cd "$(dirname "$0")/.."

PROJECT="common"
CONFIG="dev"

command -v doppler >/dev/null 2>&1 || { echo "gen-secrets: doppler CLI not found" >&2; exit 1; }

ssid=$(doppler secrets get WIFI_SSID --plain --project "$PROJECT" --config "$CONFIG")
pass=$(doppler secrets get WIFI_PASSWORD --plain --project "$PROJECT" --config "$CONFIG")

# Written via Python so the secret is quoted with repr() - a password
# containing quotes, backslashes or $ cannot break the generated file.
umask 077
WIFI_SSID_VALUE="$ssid" WIFI_PASSWORD_VALUE="$pass" python3 - <<'PY'
import os
import pathlib

ssid = os.environ["WIFI_SSID_VALUE"]
password = os.environ["WIFI_PASSWORD_VALUE"]

pathlib.Path("config_secrets.py").write_text(
    '"""Device-local secrets - GENERATED by scripts/gen-secrets.sh.\n'
    "\n"
    "Do not edit by hand: edit the values in Doppler (project\n"
    "'common', config 'dev') and re-run the script. This file is\n"
    "gitignored and must never be committed.\n"
    '"""\n'
    "\n"
    f"WIFI_SSID = {ssid!r}\n"
    f"WIFI_PASSWORD = {password!r}\n"
)
PY

echo "gen-secrets: wrote config_secrets.py (ssid=${ssid})"
echo "gen-secrets: deploy with  mpremote connect \"\$(scripts/find-board.sh)\" fs cp config_secrets.py :"
