#!/usr/bin/env bash
# Regenerate the gitignored config_secrets.py from Doppler.
#
# Source of truth: Doppler project `common`, config `dev` (shared across
# projects - the house WiFi is not specific to this repo). Run once after a
# container rebuild, or whenever the credentials change:
#
#     ./scripts/gen-secrets.sh
#
# config_secrets.py is gitignored, so this file - not the secret - is what
# survives in git. The board needs a real file on its filesystem, so the
# generated output is then deployed with `mpremote fs cp config_secrets.py :`.
set -euo pipefail

cd "$(dirname "$0")/.."

PROJECT="common"
CONFIG="dev"

command -v doppler >/dev/null 2>&1 || { echo "gen-secrets: doppler CLI not found" >&2; exit 1; }

ssid=$(doppler secrets get WIFI_SSID --plain --project "$PROJECT" --config "$CONFIG")
pass=$(doppler secrets get WIFI_PASSWORD --plain --project "$PROJECT" --config "$CONFIG")

# Optional. A missing secret is not an error: without them the board uses DHCP,
# exactly as before. The router RESERVES this address for the board's MAC, which
# is what makes a fixed address safe here (see config.py).
get_opt() { doppler secrets get "$1" --plain --project "$PROJECT" --config "$CONFIG" 2>/dev/null || true; }
s_ip=$(get_opt STATIC_IP)
s_mask=$(get_opt STATIC_MASK)
s_gw=$(get_opt STATIC_GATEWAY)
s_dns=$(get_opt STATIC_DNS)

# Written via Python so the secret is quoted with repr() - a password
# containing quotes, backslashes or $ cannot break the generated file.
umask 077
WIFI_SSID_VALUE="$ssid" WIFI_PASSWORD_VALUE="$pass" \
STATIC_IP_VALUE="$s_ip" STATIC_MASK_VALUE="$s_mask" \
STATIC_GATEWAY_VALUE="$s_gw" STATIC_DNS_VALUE="$s_dns" python3 - <<'PY'
import os
import pathlib

ssid = os.environ["WIFI_SSID_VALUE"]
password = os.environ["WIFI_PASSWORD_VALUE"]

# Emitted only when all four are present: a half-configured address would be
# worse than DHCP.
want_static = all(
    os.environ.get(name)
    for name in ("STATIC_IP_VALUE", "STATIC_MASK_VALUE",
                 "STATIC_GATEWAY_VALUE", "STATIC_DNS_VALUE")
)
static = ""
if want_static:
    static = (
        "\n"
        "# The address the router RESERVES for this board's MAC. Set only\n"
        "# because DHCP stalls here (status=2, associated, no IP).\n"
        f"STATIC_IP = {os.environ['STATIC_IP_VALUE']!r}\n"
        f"STATIC_MASK = {os.environ['STATIC_MASK_VALUE']!r}\n"
        f"STATIC_GATEWAY = {os.environ['STATIC_GATEWAY_VALUE']!r}\n"
        f"STATIC_DNS = {os.environ['STATIC_DNS_VALUE']!r}\n"
    )

pathlib.Path("config_secrets.py").write_text(
    '"""Device-local secrets - GENERATED by scripts/gen-secrets.sh.\n'
    "\n"
    "Do not edit by hand: edit the values in Doppler (project\n"
    "'common', config 'dev') and re-run the script. This file is\n"
    "gitignored and must never be committed.\n"
    '"""\n'
    "\n"
    f"WIFI_SSID = {ssid!r}\n"
    f"WIFI_PASSWORD = {password!r}\n"
    + static
)
PY

echo "gen-secrets: wrote config_secrets.py (ssid=${ssid}, static=${s_ip:-<dhcp>})"
echo "gen-secrets: deploy with  mpremote connect \"\$(scripts/find-board.sh)\" fs cp config_secrets.py :"
